### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by yury**
Hi,

- I added arm64 architecture to simulators. 
- Enabled bitcode
- Updated build

To make it work, I pointed to my fork of ios_system release https://github.com/yury/ios_system/releases
After merge, please update url in checksum in `xcfs/Package.swift`

### CODE REVIEW

**Comment by holzschu** [comment]
Both before and after editing `xcfs/Package.swift`, I get: 
```
error: artifact of binary target 'ios_system' has changed checksum; this is a potential security risk so the new artifact won't be downloaded
```

**Comment by yury** [comment]
Yes, but now you can use work around.

1. Comment binaryTarget that you want to update
2. run `swift package update`
3. Uncomment and update checksum
4. run `swift package update`

This allows you to update only packages you want to update. Not all packages.

**Comment by holzschu** [comment]
I must have missed something, because I did all this and I still get: 
```
error: artifact of binary target 'ios_system' has changed checksum; this is a potential security risk so the new artifact won't be downloaded
```
My `xcfs/Package.swift` refers to the newly built `ios_system`:
```
        .binaryTarget(
            name: "ios_system",
            url: "https://github.com/holzschu/ios_system/releases/download/v2.7.0/ios_system.xcframework.zip",
            checksum: "83545ba08c01d0ea813fa48133efd64f734a0c3900e8e123188e9e9d2907ca90"
        ),
```
I must be missing something, but I don't know what it is.

**Comment by holzschu** [comment]
After a combination of `swift package reset`, `resolve`, `update` and `clean`, the framework is now built (I don't know which one made the trick).

**Pull request merged**
